package org.joget.workflow.shark;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.LinkedHashMap;
import javax.sql.DataSource;
import java.lang.reflect.Field;
import org.aspectj.lang.ProceedingJoinPoint;
import org.aspectj.lang.annotation.Around;
import org.aspectj.lang.annotation.Aspect;
import org.enhydra.shark.api.client.wfmc.wapi.WMSessionHandle;
import org.enhydra.shark.instancepersistence.data.ActivityDO;
import org.enhydra.shark.instancepersistence.data.ActivityDataDO;
import org.enhydra.shark.instancepersistence.data.ActivityDataQuery;
import org.enhydra.shark.instancepersistence.data.ActivityQuery;
import org.enhydra.shark.instancepersistence.data.ProcessDO;
import org.enhydra.shark.instancepersistence.data.ProcessDataDO;
import org.enhydra.shark.instancepersistence.data.ProcessDataQuery;
import org.enhydra.shark.instancepersistence.data.ProcessQuery;
import org.joget.commons.util.LogUtil;
import org.joget.workflow.util.WorkflowUtil;
import org.springframework.jdbc.datasource.DataSourceUtils;

/**
 * AOP aspect that batches individual SQL statements generated by the Shark engine
 * when persisting workflow variable data during activity and process context saves.
 *
 * Without this aspect, WfActivityImpl.persistActivityContext() and
 * WfProcessImpl.persistProcessContext() each call DODSPersistentManager.persist()
 * once per variable, resulting in N individual round-trips per completion.
 *
 * This aspect intercepts:
 *   1. WfActivityImpl.persistActivityContext() — batches SHKActivityData INSERTs/UPDATEs
 *   2. WfProcessImpl.persistProcessContext()   — batches SHKProcessData INSERTs/UPDATEs
 *   3. ActivityDataDO.save(boolean)            — routes to INSERT or UPDATE buffer
 *   4. ProcessDataDO.save(boolean)             — routes to INSERT or UPDATE buffer
 *   5-9. getPersistedXxxObject calls           — caches parent-row and variable-row lookups
 *
 * Deployment: drop the JAR into WEB-INF/lib. The bundled META-INF/aop.xml is
 * auto-discovered by AspectJ's load-time weaver — no changes to the main aop.xml needed.
 */
@Aspect
public class VariableDataBatchAspect {

    private static final String LOG_CLASS = VariableDataBatchAspect.class.getName();

    // ---- Activity-side ThreadLocals (active during persistActivityContext) ----

    /** Virgin ActivityDataDO rows buffered for a single batch INSERT. */
    private static final ThreadLocal<List<ActivityDataDO>> insertBuffer = new ThreadLocal<>();

    /** Non-virgin ActivityDataDO rows buffered for a single batch UPDATE. */
    private static final ThreadLocal<List<ActivityDataDO>> updateBuffer = new ThreadLocal<>();

    /** Cache: activityId → ActivityDO (avoids N identical SHKActivities SELECTs). */
    private static final ThreadLocal<Map<String, Object>> activityCache = new ThreadLocal<>();

    /**
     * Cache: activityId → (varDefId → list of ActivityDataDO).
     * Populated once per activityId by a single bulk SELECT; served from memory thereafter.
     */
    private static final ThreadLocal<Map<String, Map<String, List<ActivityDataDO>>>> activityDataCache = new ThreadLocal<>();

    // ---- Process-side ThreadLocals (active during persistProcessContext) ----

    /** Virgin ProcessDataDO rows buffered for a single batch INSERT. */
    private static final ThreadLocal<List<ProcessDataDO>> processDataInsertBuffer = new ThreadLocal<>();

    /** Non-virgin ProcessDataDO rows buffered for a single batch UPDATE. */
    private static final ThreadLocal<List<ProcessDataDO>> processDataUpdateBuffer = new ThreadLocal<>();

    /** Cache: processId → ProcessDO (avoids N identical SHKProcesses SELECTs). */
    private static final ThreadLocal<Map<String, Object>> processCache = new ThreadLocal<>();

    /**
     * Cache: processId → (varDefId → list of ProcessDataDO).
     * Populated once per processId by a single bulk SELECT; served from memory thereafter.
     */
    private static final ThreadLocal<Map<String, Map<String, List<ProcessDataDO>>>> processDataCache = new ThreadLocal<>();

    static {
        LogUtil.info(LOG_CLASS, "VariableDataBatchAspect loaded — SHKActivityData and SHKProcessData statements will be batched");
    }

    // =========================================================================
    // Pointcut 1: wrap persistActivityContext() — activate/flush activity batch
    // =========================================================================

    @Around("execution(* org.enhydra.shark.WfActivityImpl.persistActivityContext(..))")
    public Object aroundPersistActivityContext(ProceedingJoinPoint pjp) throws Throwable {
        LogUtil.debug(LOG_CLASS, "Batch mode activated for persistActivityContext");
        insertBuffer.set(new ArrayList<ActivityDataDO>());
        updateBuffer.set(new ArrayList<ActivityDataDO>());
        activityCache.set(new HashMap<String, Object>());
        activityDataCache.set(new HashMap<String, Map<String, List<ActivityDataDO>>>());
        try {
            filterUnchangedActivityVariables(pjp);
            pjp.proceed();
            flushBatch();
            flushUpdateBatch();
        } finally {
            insertBuffer.remove();
            updateBuffer.remove();
            activityCache.remove();
            activityDataCache.remove();
        }
        return null;
    }

    // =========================================================================
    // Pointcut 2: wrap persistProcessContext() — activate/flush process batch
    // =========================================================================

    @Around("execution(* org.enhydra.shark.WfProcessImpl.persistProcessContext(..))")
    public Object aroundPersistProcessContext(ProceedingJoinPoint pjp) throws Throwable {
        LogUtil.debug(LOG_CLASS, "Batch mode activated for persistProcessContext");
        processDataInsertBuffer.set(new ArrayList<ProcessDataDO>());
        processDataUpdateBuffer.set(new ArrayList<ProcessDataDO>());
        processCache.set(new HashMap<String, Object>());
        processDataCache.set(new HashMap<String, Map<String, List<ProcessDataDO>>>());
        try {
            pjp.proceed();
            flushProcessDataInsertBatch();
            flushProcessDataUpdateBatch();
        } finally {
            processDataInsertBuffer.remove();
            processDataUpdateBuffer.remove();
            processCache.remove();
            processDataCache.remove();
        }
        return null;
    }

    // =========================================================================
    // Pointcut 3: route ActivityDataDO.save(boolean) to INSERT or UPDATE buffer
    // =========================================================================

    @Around("execution(* org.enhydra.shark.instancepersistence.data.ActivityDataDO.save(boolean))")
    public Object aroundActivityDataSave(ProceedingJoinPoint pjp) throws Throwable {
        ActivityDataDO doObj = (ActivityDataDO) pjp.getThis();
        if (doObj.isVirgin()) {
            List<ActivityDataDO> buffer = insertBuffer.get();
            if (buffer != null) {
                buffer.add(doObj);
                return null; // suppress individual INSERT
            }
        } else {
            List<ActivityDataDO> buffer = updateBuffer.get();
            if (buffer != null) {
                buffer.add(doObj);
                return null; // suppress individual UPDATE
            }
        }
        return pjp.proceed();
    }

    // =========================================================================
    // Pointcut 4: route ProcessDataDO.save(boolean) to INSERT or UPDATE buffer
    // =========================================================================

    @Around("execution(* org.enhydra.shark.instancepersistence.data.ProcessDataDO.save(boolean))")
    public Object aroundProcessDataSave(ProceedingJoinPoint pjp) throws Throwable {
        ProcessDataDO doObj = (ProcessDataDO) pjp.getThis();
        if (doObj.isVirgin()) {
            List<ProcessDataDO> buffer = processDataInsertBuffer.get();
            if (buffer != null) {
                buffer.add(doObj);
                return null; // suppress individual INSERT
            }
        } else {
            List<ProcessDataDO> buffer = processDataUpdateBuffer.get();
            if (buffer != null) {
                buffer.add(doObj);
                return null; // suppress individual UPDATE
            }
        }
        return pjp.proceed();
    }

    // =========================================================================
    // Pointcut 5: cache getPersistedActivityObject within persistActivityContext
    // =========================================================================

    @Around("execution(* org.enhydra.shark.instancepersistence.DODSPersistentManager.getPersistedActivityObject(..))")
    public Object aroundGetPersistedActivityObject(ProceedingJoinPoint pjp) throws Throwable {
        Map<String, Object> cache = activityCache.get();
        if (cache == null) return pjp.proceed();
        Object[] args = pjp.getArgs();
        if (args == null || args.length == 0 || !(args[0] instanceof String)) return pjp.proceed();
        String id = (String) args[0];
        if (cache.containsKey(id)) {
            LogUtil.debug(LOG_CLASS, "Cache hit SHKActivities id=" + id);
            return cache.get(id);
        }
        Object result = pjp.proceed();
        cache.put(id, result);
        return result;
    }

    // =========================================================================
    // Pointcut 6: cache getPersistedProcessObject within persistProcessContext
    // =========================================================================

    @Around("execution(* org.enhydra.shark.instancepersistence.DODSPersistentManager.getPersistedProcessObject(..))")
    public Object aroundGetPersistedProcessObject(ProceedingJoinPoint pjp) throws Throwable {
        Map<String, Object> cache = processCache.get();
        if (cache == null) return pjp.proceed();
        Object[] args = pjp.getArgs();
        if (args == null || args.length == 0 || !(args[0] instanceof String)) return pjp.proceed();
        String id = (String) args[0];
        if (cache.containsKey(id)) {
            LogUtil.debug(LOG_CLASS, "Cache hit SHKProcesses id=" + id);
            return cache.get(id);
        }
        Object result = pjp.proceed();
        cache.put(id, result);
        return result;
    }

    // =========================================================================
    // Pointcut 7: cache getPersistedActivityVariableObject (scalar)
    // =========================================================================

    @Around("execution(* org.enhydra.shark.instancepersistence.DODSPersistentManager.getPersistedActivityVariableObject(..))")
    public Object aroundGetPersistedActivityVariableObject(ProceedingJoinPoint pjp) throws Throwable {
        Map<String, Map<String, List<ActivityDataDO>>> dataCache = activityDataCache.get();
        if (dataCache == null) return pjp.proceed();
        Object[] args = pjp.getArgs();
        if (args == null || args.length < 2 || !(args[0] instanceof String) || !(args[1] instanceof String))
            return pjp.proceed();
        String activityId = (String) args[0];
        String varDefId   = (String) args[1];
        if (!dataCache.containsKey(activityId)) bulkLoadActivityData(activityId, dataCache);
        Map<String, List<ActivityDataDO>> varMap = dataCache.get(activityId);
        if (varMap == null) return pjp.proceed();
        List<ActivityDataDO> list = varMap.get(varDefId);
        return (list != null && !list.isEmpty()) ? list.get(0) : null;
    }

    // =========================================================================
    // Pointcut 8: cache getPersistedActivityVariableObjects (array)
    // =========================================================================

    @Around("execution(* org.enhydra.shark.instancepersistence.DODSPersistentManager.getPersistedActivityVariableObjects(..))")
    public Object aroundGetPersistedActivityVariableObjects(ProceedingJoinPoint pjp) throws Throwable {
        Map<String, Map<String, List<ActivityDataDO>>> dataCache = activityDataCache.get();
        if (dataCache == null) return pjp.proceed();
        Object[] args = pjp.getArgs();
        if (args == null || args.length < 2 || !(args[0] instanceof String) || !(args[1] instanceof String))
            return pjp.proceed();
        String activityId = (String) args[0];
        String varDefId   = (String) args[1];
        if (!dataCache.containsKey(activityId)) bulkLoadActivityData(activityId, dataCache);
        Map<String, List<ActivityDataDO>> varMap = dataCache.get(activityId);
        if (varMap == null) return pjp.proceed();
        List<ActivityDataDO> list = varMap.getOrDefault(varDefId, Collections.emptyList());
        return list.toArray(new ActivityDataDO[0]);
    }

    // =========================================================================
    // Pointcut 9: cache getPersistedProcessVariableObject (scalar)
    // =========================================================================

    @Around("execution(* org.enhydra.shark.instancepersistence.DODSPersistentManager.getPersistedProcessVariableObject(..))")
    public Object aroundGetPersistedProcessVariableObject(ProceedingJoinPoint pjp) throws Throwable {
        Map<String, Map<String, List<ProcessDataDO>>> dataCache = processDataCache.get();
        if (dataCache == null) return pjp.proceed();
        Object[] args = pjp.getArgs();
        if (args == null || args.length < 2 || !(args[0] instanceof String) || !(args[1] instanceof String))
            return pjp.proceed();
        String processId = (String) args[0];
        String varDefId  = (String) args[1];
        if (!dataCache.containsKey(processId)) bulkLoadProcessData(processId, dataCache);
        Map<String, List<ProcessDataDO>> varMap = dataCache.get(processId);
        if (varMap == null) return pjp.proceed();
        List<ProcessDataDO> list = varMap.get(varDefId);
        return (list != null && !list.isEmpty()) ? list.get(0) : null;
    }

    // =========================================================================
    // Pointcut 10: cache getPersistedProcessVariableObjects (array)
    // =========================================================================

    @Around("execution(* org.enhydra.shark.instancepersistence.DODSPersistentManager.getPersistedProcessVariableObjects(..))")
    public Object aroundGetPersistedProcessVariableObjects(ProceedingJoinPoint pjp) throws Throwable {
        Map<String, Map<String, List<ProcessDataDO>>> dataCache = processDataCache.get();
        if (dataCache == null) return pjp.proceed();
        Object[] args = pjp.getArgs();
        if (args == null || args.length < 2 || !(args[0] instanceof String) || !(args[1] instanceof String))
            return pjp.proceed();
        String processId = (String) args[0];
        String varDefId  = (String) args[1];
        if (!dataCache.containsKey(processId)) bulkLoadProcessData(processId, dataCache);
        Map<String, List<ProcessDataDO>> varMap = dataCache.get(processId);
        if (varMap == null) return pjp.proceed();
        List<ProcessDataDO> list = varMap.getOrDefault(varDefId, Collections.emptyList());
        return list.toArray(new ProcessDataDO[0]);
    }


    // =========================================================================
    // Pointcut 11: log activitiesProcessContext before setActivityVariables
    // =========================================================================

    @Around("execution(* org.enhydra.shark.WfActivityImpl.setActivityVariables(..))")
    public Object aroundSetActivityVariables(ProceedingJoinPoint pjp) throws Throwable  {
        Object target = pjp.getThis();
        Object result = pjp.proceed();

        try {
            @SuppressWarnings("unchecked")
            Map<String, Object> context = (Map<String, Object>) readField(target, "activitiesProcessContext");
            if (context == null) {
                LogUtil.debug(LOG_CLASS, "setActivityVariables: activitiesProcessContext is null");
            } else {
                WMSessionHandle shandle = (WMSessionHandle) pjp.getArgs()[0];
                if (shandle != null) {
                    java.lang.reflect.Method getDefMethod = findDeclaredMethod(target.getClass(), "getProcessDefinition",
                            org.enhydra.shark.api.client.wfmc.wapi.WMSessionHandle.class);
                    getDefMethod.setAccessible(true);
                    Object wp = getDefMethod.invoke(target, shandle);
                    if (wp != null) {
                        @SuppressWarnings("unchecked")
                        Map<String, Object> allVars = (Map<String, Object>)
                                wp.getClass().getMethod("getAllVariables").invoke(wp);
                        if (allVars != null) {
                            int added = 0;
                            for (String varId : allVars.keySet()) {
                                if (!context.containsKey(varId)) {
                                    context.put(varId, null);
                                    added++;
                                }
                            }
                            if (added > 0) {
                                LogUtil.debug(LOG_CLASS, "setActivityVariables: added " + added + " missing variable(s) to activitiesProcessContext");
                            }
                        }
                    }
                }
            }
        } catch (Exception e) {
            LogUtil.warn(LOG_CLASS, "setActivityVariables: could not read activitiesProcessContext — " + e.getMessage());
        }

        return result;
    }

    // =========================================================================
    // Bulk pre-fetch helpers
    // =========================================================================

    /**
     * Pre-fetch ALL SHKActivityData rows for the given activity with a single query.
     * Falls back to an ActivityQuery lookup when the ActivityDO isn't in activityCache yet.
     */
    private void bulkLoadActivityData(String activityId,
            Map<String, Map<String, List<ActivityDataDO>>> dataCache) {
        Map<String, List<ActivityDataDO>> varMap = new HashMap<>();
        dataCache.put(activityId, varMap); // register immediately to block re-entry
        try {
            Map<String, Object> aCache = activityCache.get();
            Object actObj = (aCache != null) ? aCache.get(activityId) : null;
            ActivityDO actDO;
            if (actObj instanceof ActivityDO) {
                actDO = (ActivityDO) actObj;
            } else {
                ActivityQuery aq = new ActivityQuery();
                aq.setQueryId(activityId);
                ActivityDO[] acts = aq.getDOArray();
                if (acts == null || acts.length == 0) {
                    LogUtil.debug(LOG_CLASS, "Activity not found in DB for id=" + activityId + " — skipping bulk pre-fetch");
                    return;
                }
                actDO = acts[0];
                if (aCache != null) aCache.put(activityId, actDO);
            }
            ActivityDataQuery q = new ActivityDataQuery();
            q.setQueryActivity(actDO);
            ActivityDataDO[] all = q.getDOArray();
            for (ActivityDataDO row : all) {
                String vid = row.getVariableDefinitionId();
                varMap.computeIfAbsent(vid, k -> new ArrayList<>()).add(row);
            }
            LogUtil.debug(LOG_CLASS, "Bulk pre-fetched " + all.length + " SHKActivityData rows for activity=" + activityId);
        } catch (Exception e) {
            LogUtil.error(LOG_CLASS, e, "Bulk pre-fetch of SHKActivityData failed for activity=" + activityId);
            dataCache.remove(activityId);
        }
    }

    /**
     * Pre-fetch ALL SHKProcessData rows for the given process with a single query.
     * Falls back to a ProcessQuery lookup when the ProcessDO isn't in processCache yet.
     */
    private void bulkLoadProcessData(String processId,
            Map<String, Map<String, List<ProcessDataDO>>> dataCache) {
        Map<String, List<ProcessDataDO>> varMap = new HashMap<>();
        dataCache.put(processId, varMap); // register immediately to block re-entry
        try {
            Map<String, Object> pCache = processCache.get();
            Object procObj = (pCache != null) ? pCache.get(processId) : null;
            ProcessDO procDO;
            if (procObj instanceof ProcessDO) {
                procDO = (ProcessDO) procObj;
            } else {
                ProcessQuery pq = new ProcessQuery();
                pq.setQueryId(processId);
                ProcessDO[] procs = pq.getDOArray();
                if (procs == null || procs.length == 0) {
                    LogUtil.debug(LOG_CLASS, "Process not found in DB for id=" + processId + " — skipping bulk pre-fetch");
                    return;
                }
                procDO = procs[0];
                if (pCache != null) pCache.put(processId, procDO);
            }
            ProcessDataQuery q = new ProcessDataQuery();
            q.setQueryProcess(procDO);
            ProcessDataDO[] all = q.getDOArray();
            for (ProcessDataDO row : all) {
                String vid = row.getVariableDefinitionId();
                varMap.computeIfAbsent(vid, k -> new ArrayList<>()).add(row);
            }
            LogUtil.debug(LOG_CLASS, "Bulk pre-fetched " + all.length + " SHKProcessData rows for process=" + processId);
        } catch (Exception e) {
            LogUtil.error(LOG_CLASS, e, "Bulk pre-fetch of SHKProcessData failed for process=" + processId);
            dataCache.remove(processId);
        }
    }

    // =========================================================================
    // Changed-value filter: skip unchanged activity variables before persist
    // =========================================================================

    /**
     * Before persistActivityContext proceeds, compare each variable in
     * variableIdsToPersist against the already-persisted VariableValueVCHAR.
     * Variables whose value has not changed are removed from the set so the
     * engine never issues an INSERT/UPDATE for them.
     *
     * Only applied for activity context — process context is left untouched.
     */
    @SuppressWarnings("unchecked")
    private void filterUnchangedActivityVariables(ProceedingJoinPoint pjp) {
        try {
            Object target = pjp.getThis();

            // Get activity ID and the mutable set of variable IDs to persist
            String activityId = (String) readField(target, "key");
            Set<String> varIds = (Set<String>) readField(target, "variableIdsToPersist");
            if (varIds == null || varIds.isEmpty()) return;

            // Pre-load the activity data cache so we can compare without extra queries
            Map<String, Map<String, List<ActivityDataDO>>> dataCache = activityDataCache.get();
            if (!dataCache.containsKey(activityId)) {
                bulkLoadActivityData(activityId, dataCache);
            }
            Map<String, List<ActivityDataDO>> varMap = dataCache.get(activityId);

            // Read the current in-memory context map directly from the field
            Map<String, Object> currentContext = (Map<String, Object>) readField(target, "activitiesProcessContext");
            if (currentContext == null) return;

            // Remove variables whose VCHAR value is identical to what is already in DB
            Set<String> toRemove = new HashSet<String>();
            for (String varId : varIds) {
                Object currentVal = currentContext.get(varId);
                
                List<ActivityDataDO> existingList = varMap.get(varId);
                if (existingList == null || existingList.isEmpty()) {
                    // No persisted row yet — only INSERT if the variable has a value
                    if (currentVal == null ||  String.valueOf(currentVal).isEmpty()) {
                        toRemove.add(varId);
                    }
                    continue;
                }
                String persistedVchar = existingList.get(0).getVariableValueVCHAR();
                String currentVchar = (currentVal != null) ? String.valueOf(currentVal) : null;
                if (isVcharEqual(persistedVchar, currentVchar)) {
                    toRemove.add(varId);
                }
            }

            if (!toRemove.isEmpty()) {
                varIds.removeAll(toRemove);
                LogUtil.debug(LOG_CLASS, "Skipped " + toRemove.size() + " unchanged variable(s) for activity=" + activityId + ": " + toRemove);
            }
        } catch (Exception e) {
            LogUtil.warn(LOG_CLASS, "filterUnchangedActivityVariables failed — proceeding without filter: " + e.getMessage());
        }
    }

    private boolean isVcharEqual(String a, String b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        return a.equals(b);
    }

    // =========================================================================
    // Flush: batch INSERT SHKActivityData
    // =========================================================================

    private void flushBatch() {
        List<ActivityDataDO> buffer = insertBuffer.get();
        if (buffer == null || buffer.isEmpty()) return;
        DataSource ds = (DataSource) WorkflowUtil.getApplicationContext().getBean("setupDataSource");
        Connection conn = null;
        PreparedStatement ps = null;
        int batchSize = buffer.size();
        try {
            conn = DataSourceUtils.getConnection(ds);
            String sql = "INSERT INTO SHKActivityData"
                    + " (Activity, VariableDefinitionId, VariableType,"
                    + " VariableValue, VariableValueXML, VariableValueVCHAR,"
                    + " VariableValueDBL, VariableValueLONG, VariableValueDATE,"
                    + " VariableValueBOOL, IsResult, OrdNo, CNT, oid, version)"
                    + " VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            ps = conn.prepareStatement(sql);
            for (ActivityDataDO doObj : buffer) {
                populateActivityInsertStatement(ps, doObj);
                ps.addBatch();
            }
            ps.executeBatch();
            for (ActivityDataDO doObj : buffer) {
                writeField(doObj, "persistent", true);
                writeField(doObj, "dirty", false);
            }
            LogUtil.debug(LOG_CLASS, "Batch inserted " + batchSize + " SHKActivityData rows");
        } catch (Exception e) {
            LogUtil.error(LOG_CLASS, e, "Batch INSERT SHKActivityData failed (" + batchSize + " rows) — falling back");
            fallbackSaves(buffer, insertBuffer);
        } finally {
            closeQuietly(ps, conn, ds);
        }
    }

    private void populateActivityInsertStatement(PreparedStatement ps, ActivityDataDO doObj) throws Exception {
        ps.setBigDecimal(1, doObj.oid_getActivity());
        ps.setString(2, doObj.getVariableDefinitionId());
        ps.setShort(3, doObj.getVariableType());
        setBytes(ps, 4, doObj.getVariableValue());
        setString(ps, 5, doObj.getStringVariableValueXML());
        setString(ps, 6, doObj.getVariableValueVCHAR());
        setDouble(ps, 7, doObj.getVariableType(), 2, doObj.getVariableValueDBL());
        setLong(ps, 8, doObj.getVariableType(), 1, doObj.getVariableValueLONG());
        setTimestamp(ps, 9, doObj.getVariableValueDATE());
        setBoolean(ps, 10, doObj.getVariableType(), 0, doObj.getVariableValueBOOL());
        ps.setBoolean(11, doObj.getIsResult());
        ps.setInt(12, doObj.getOrdNo());
        ps.setBigDecimal(13, doObj.getCNT());
        ps.setBigDecimal(14, doObj.get_OId().toBigDecimal());
        ps.setInt(15, 0);
    }

    // =========================================================================
    // Flush: batch UPDATE SHKActivityData
    // =========================================================================

    private void flushUpdateBatch() {
        List<ActivityDataDO> buffer = updateBuffer.get();
        if (buffer == null || buffer.isEmpty()) return;
        DataSource ds = (DataSource) WorkflowUtil.getApplicationContext().getBean("setupDataSource");
        Connection conn = null;
        PreparedStatement ps = null;
        int batchSize = buffer.size();
        try {
            conn = DataSourceUtils.getConnection(ds);
            String sql = "UPDATE SHKActivityData SET"
                    + " version=?, VariableValue=?, VariableValueXML=?, VariableValueVCHAR=?,"
                    + " VariableValueDBL=?, VariableValueLONG=?, VariableValueDATE=?,"
                    + " VariableValueBOOL=?, IsResult=?"
                    + " WHERE oid=? AND version=?";
            ps = conn.prepareStatement(sql);
            for (ActivityDataDO doObj : buffer) {
                populateActivityUpdateStatement(ps, doObj);
                ps.addBatch();
            }
            ps.executeBatch();
            LogUtil.debug(LOG_CLASS, "Batch updated " + batchSize + " SHKActivityData rows");
        } catch (Exception e) {
            LogUtil.error(LOG_CLASS, e, "Batch UPDATE SHKActivityData failed (" + batchSize + " rows) — falling back");
            fallbackSaves(buffer, updateBuffer);
        } finally {
            closeQuietly(ps, conn, ds);
        }
    }

    private void populateActivityUpdateStatement(PreparedStatement ps, ActivityDataDO doObj) throws Exception {
        ps.setInt(1, doObj.get_NewVersion());
        setBytes(ps, 2, doObj.getVariableValue());
        setString(ps, 3, doObj.getStringVariableValueXML());
        setString(ps, 4, doObj.getVariableValueVCHAR());
        setDouble(ps, 5, doObj.getVariableType(), 2, doObj.getVariableValueDBL());
        setLong(ps, 6, doObj.getVariableType(), 1, doObj.getVariableValueLONG());
        setTimestamp(ps, 7, doObj.getVariableValueDATE());
        setBoolean(ps, 8, doObj.getVariableType(), 0, doObj.getVariableValueBOOL());
        ps.setBoolean(9, doObj.getIsResult());
        ps.setBigDecimal(10, doObj.get_OId().toBigDecimal());
        ps.setInt(11, doObj.get_Version());
    }

    // =========================================================================
    // Flush: batch INSERT SHKProcessData
    // =========================================================================

    private void flushProcessDataInsertBatch() {
        List<ProcessDataDO> buffer = processDataInsertBuffer.get();
        if (buffer == null || buffer.isEmpty()) return;
        DataSource ds = (DataSource) WorkflowUtil.getApplicationContext().getBean("setupDataSource");
        Connection conn = null;
        PreparedStatement ps = null;
        int batchSize = buffer.size();
        try {
            conn = DataSourceUtils.getConnection(ds);
            String sql = "INSERT INTO SHKProcessData"
                    + " (Process, VariableDefinitionId, VariableType,"
                    + " VariableValue, VariableValueXML, VariableValueVCHAR,"
                    + " VariableValueDBL, VariableValueLONG, VariableValueDATE,"
                    + " VariableValueBOOL, OrdNo, CNT, oid, version)"
                    + " VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            ps = conn.prepareStatement(sql);
            for (ProcessDataDO doObj : buffer) {
                populateProcessDataInsertStatement(ps, doObj);
                ps.addBatch();
            }
            ps.executeBatch();
            for (ProcessDataDO doObj : buffer) {
                writeField(doObj, "persistent", true);
                writeField(doObj, "dirty", false);
            }
            LogUtil.debug(LOG_CLASS, "Batch inserted " + batchSize + " SHKProcessData rows");
        } catch (Exception e) {
            LogUtil.error(LOG_CLASS, e, "Batch INSERT SHKProcessData failed (" + batchSize + " rows) — falling back");
            fallbackSaves(buffer, processDataInsertBuffer);
        } finally {
            closeQuietly(ps, conn, ds);
        }
    }

    private void populateProcessDataInsertStatement(PreparedStatement ps, ProcessDataDO doObj) throws Exception {
        ps.setBigDecimal(1, doObj.oid_getProcess());
        ps.setString(2, doObj.getVariableDefinitionId());
        ps.setShort(3, doObj.getVariableType());
        setBytes(ps, 4, doObj.getVariableValue());
        setString(ps, 5, doObj.getStringVariableValueXML());
        setString(ps, 6, doObj.getVariableValueVCHAR());
        setDouble(ps, 7, doObj.getVariableType(), 2, doObj.getVariableValueDBL());
        setLong(ps, 8, doObj.getVariableType(), 1, doObj.getVariableValueLONG());
        setTimestamp(ps, 9, doObj.getVariableValueDATE());
        setBoolean(ps, 10, doObj.getVariableType(), 0, doObj.getVariableValueBOOL());
        ps.setInt(11, doObj.getOrdNo());
        ps.setBigDecimal(12, doObj.getCNT());
        ps.setBigDecimal(13, doObj.get_OId().toBigDecimal());
        ps.setInt(14, 0);
    }

    // =========================================================================
    // Flush: batch UPDATE SHKProcessData
    // =========================================================================

    private void flushProcessDataUpdateBatch() {
        List<ProcessDataDO> buffer = processDataUpdateBuffer.get();
        if (buffer == null || buffer.isEmpty()) return;
        DataSource ds = (DataSource) WorkflowUtil.getApplicationContext().getBean("setupDataSource");
        Connection conn = null;
        PreparedStatement ps = null;
        int batchSize = buffer.size();
        try {
            conn = DataSourceUtils.getConnection(ds);
            String sql = "UPDATE SHKProcessData SET"
                    + " version=?, VariableValue=?, VariableValueXML=?, VariableValueVCHAR=?,"
                    + " VariableValueDBL=?, VariableValueLONG=?, VariableValueDATE=?,"
                    + " VariableValueBOOL=?"
                    + " WHERE oid=? AND version=?";
            ps = conn.prepareStatement(sql);
            for (ProcessDataDO doObj : buffer) {
                populateProcessDataUpdateStatement(ps, doObj);
                ps.addBatch();
            }
            ps.executeBatch();
            LogUtil.debug(LOG_CLASS, "Batch updated " + batchSize + " SHKProcessData rows");
        } catch (Exception e) {
            LogUtil.error(LOG_CLASS, e, "Batch UPDATE SHKProcessData failed (" + batchSize + " rows) — falling back");
            fallbackSaves(buffer, processDataUpdateBuffer);
        } finally {
            closeQuietly(ps, conn, ds);
        }
    }

    private void populateProcessDataUpdateStatement(PreparedStatement ps, ProcessDataDO doObj) throws Exception {
        ps.setInt(1, doObj.get_NewVersion());
        setBytes(ps, 2, doObj.getVariableValue());
        setString(ps, 3, doObj.getStringVariableValueXML());
        setString(ps, 4, doObj.getVariableValueVCHAR());
        setDouble(ps, 5, doObj.getVariableType(), 2, doObj.getVariableValueDBL());
        setLong(ps, 6, doObj.getVariableType(), 1, doObj.getVariableValueLONG());
        setTimestamp(ps, 7, doObj.getVariableValueDATE());
        setBoolean(ps, 8, doObj.getVariableType(), 0, doObj.getVariableValueBOOL());
        ps.setBigDecimal(9, doObj.get_OId().toBigDecimal());
        ps.setInt(10, doObj.get_Version());
    }

    // =========================================================================
    // Fallback helpers
    // =========================================================================

    private <T> void fallbackSaves(List<T> buffer, ThreadLocal<List<T>> tl) {
        tl.remove(); // prevent re-interception
        for (T doObj : buffer) {
            try {
                doObj.getClass().getMethod("save", boolean.class).invoke(doObj, false);
            } catch (Exception e) {
                LogUtil.error(LOG_CLASS, e, "Fallback individual save also failed for " + doObj.getClass().getSimpleName());
            }
        }
    }

    // =========================================================================
    // PreparedStatement helpers
    // =========================================================================

    private void setBytes(PreparedStatement ps, int idx, byte[] val) throws SQLException {
        if (val != null) ps.setBytes(idx, val);
        else ps.setNull(idx, java.sql.Types.BINARY);
    }

    private void setString(PreparedStatement ps, int idx, String val) throws SQLException {
        if (val != null) ps.setString(idx, val);
        else ps.setNull(idx, java.sql.Types.VARCHAR);
    }

    private void setDouble(PreparedStatement ps, int idx, short type, int dblType, double val) throws SQLException {
        if (type == dblType) ps.setDouble(idx, val);
        else ps.setNull(idx, java.sql.Types.DOUBLE);
    }

    private void setLong(PreparedStatement ps, int idx, short type, int longType, long val) throws SQLException {
        if (type == longType) ps.setLong(idx, val);
        else ps.setNull(idx, java.sql.Types.BIGINT);
    }

    private void setTimestamp(PreparedStatement ps, int idx, Timestamp val) throws SQLException {
        if (val != null) ps.setTimestamp(idx, val);
        else ps.setNull(idx, java.sql.Types.TIMESTAMP);
    }

    private void setBoolean(PreparedStatement ps, int idx, short type, int boolType, boolean val) throws SQLException {
        if (type == boolType) ps.setBoolean(idx, val);
        else ps.setNull(idx, java.sql.Types.BOOLEAN);
    }

    private void closeQuietly(PreparedStatement ps, Connection conn, DataSource ds) {
        if (ps != null) { try { ps.close(); } catch (SQLException ignored) {} }
        if (conn != null) DataSourceUtils.releaseConnection(conn, ds);
    }

    // =========================================================================
    // Reflection helpers
    // =========================================================================

    private static Object readField(Object target, String fieldName) throws Exception {
        Field field = findDeclaredField(target.getClass(), fieldName);
        field.setAccessible(true);
        return field.get(target);
    }

    private static void writeField(Object target, String fieldName, Object value) throws Exception {
        Field field = findDeclaredField(target.getClass(), fieldName);
        field.setAccessible(true);
        field.set(target, value);
    }

    private static Field findDeclaredField(Class<?> clazz, String fieldName) throws NoSuchFieldException {
        for (Class<?> c = clazz; c != null; c = c.getSuperclass()) {
            try { return c.getDeclaredField(fieldName); } catch (NoSuchFieldException ignored) {}
        }
        throw new NoSuchFieldException(fieldName);
    }

    private static java.lang.reflect.Method findDeclaredMethod(Class<?> clazz, String methodName, Class<?>... paramTypes) throws NoSuchMethodException {
        for (Class<?> c = clazz; c != null; c = c.getSuperclass()) {
            try { return c.getDeclaredMethod(methodName, paramTypes); } catch (NoSuchMethodException ignored) {}
        }
        throw new NoSuchMethodException(methodName);
    }
}
